BestRestaurants/Models/BestRestaurantsContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Models
{
  public class BestRestaurantsContext : DbContext
  {
    public DbSet<Type> Types { get; set; }
    public DbSet<Restaurant> Restaurants { get; set; }
    public DbSet<TypeRestaurant> TypeRestaurant { get; set; }

    public BestRestaurantsContext(DbContextOptions options) : base(options){}
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

BestRestaurants/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace BestRestaurants.Models
{
  public class BestRestaurantsContextFactory : IDesignTimeDbContextFactory<BestRestaurantsContext>
  {
    BestRestaurantsContext IDesignTimeDbContextFactory<BestRestaurantsContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("appsettings.json")
        .Build();

      var builder = new DbContextOptionsBuilder<BestRestaurantsContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new BestRestaurantsContext(builder.Options);
    }
  }
}

BestRestaurants/Models/Restaurant.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Restaurant 
  {

    public Restaurant()
    {
      this.JoinEntities = new HashSet<TypeRestaurant>();
    }
    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public int Rating { get; set; }
    public int Cost { get; set; }
    public string Review { get; set; }
    public virtual ICollection<TypeRestaurant> JoinEntities { get; set; }
  }
}

BestRestaurants/Models/Type.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Type
  {
    public Type()
    {
      this.JoinEntities = new HashSet<TypeRestaurant>();
    }

    public int TypeId { get; set; }
    public string TypeName { get; set; }
    public virtual ICollection<TypeRestaurant> JoinEntities { get; set; }
  }
}

BestRestaurants/Models/TypeRestaurant.cs
namespace BestRestaurants.Models
{
  public class TypeRestaurant
  {
    public int TypeRestaurantId { get; set; }
    public int TypeId { get; set; }
    public int RestaurantId { get; set; }
    public virtual Restaurant Restaurant { get; set; }
    public virtual Type Type { get; set; }
  }
}

BestRestaurants/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurants.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

BestRestaurants/Controllers/RestaurantsController.cs
using System.Collections.Generic; 
using Microsoft.EntityFrameworkCore; 
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BestRestaurants.Controllers
{
  public class RestaurantsController : Controller 
  { 

    private readonly BestRestaurantsContext _db;

    public RestaurantsController(BestRestaurantsContext db) 
    {
      _db = db; 
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.TypeId = new SelectList(_db.Types, "TypeId", "TypeName");
      return View(); 
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant); 
      _db.SaveChanges(); 
      return RedirectToAction("Index"); 
    }

    public ActionResult Details(int id)
    {
      var thisRestaurant = _db.Restaurants
      .Include(restaurant => restaurant.JoinEntities)
      .ThenInclude(join => join.Type)
      .FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges(); 
      return RedirectToAction("Index"); 
    }

    public ActionResult Delete(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant); 
      _db.SaveChanges(); 
      return RedirectToAction("Index"); 
    }

    public ActionResult AddType(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants
        .Include(restaurant => restaurant.JoinEntities)
        .ThenInclude(join => join.Restaurant)
        .FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      ViewBag.TypeId = new SelectList(_db.Types, "TypeId", "TypeName");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult AddType(Restaurant restaurant, int TypeId)
    {
      if (TypeId != 0)
      {
        _db.TypeRestaurant.Add(new TypeRestaurant() {TypeId = TypeId, RestaurantId = restaurant.RestaurantId});
        _db.SaveChanges();
      }
    return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Controllers/TypesController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BestRestaurants.Models;



namespace BestRestaurants.Controllers
{
  public class TypesController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public TypesController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Types.ToList()); 
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Type type, int RestaurantId)
    {
      _db.Types.Add(type);
      _db.SaveChanges();
      if (RestaurantId != 0)
      {
        _db.TypeRestaurant.Add(new TypeRestaurant() {TypeId = type.TypeId, RestaurantId = RestaurantId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisType = _db.Types
        .Include(type => type.JoinEntities)
        .ThenInclude (join => join.Restaurant)
        .FirstOrDefault(type => type.TypeId == id);
      return View(thisType);
    }

    public ActionResult Edit(int id)
    {
      var thisType = _db.Types.FirstOrDefault(type => type.TypeId == id);
      return View(thisType);
    }

    [HttpPost]
    public ActionResult Edit(Type type)
    {
      _db.Entry(type).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Type thisType = _db.Types.FirstOrDefault(type => type.TypeId == id);
      return View(thisType);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Type thisType = _db.Types.FirstOrDefault(type => type.TypeId == id);
      _db.Types.Remove(thisType);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Best Restaurants Tracker</h1>
<div class="jumbotron">
  <p>@Html.ActionLink("See all food types", "Index", "Types")</p>
  <p>@Html.ActionLink("Create new food type", "Create", "Types")</p>
  <p>@Html.ActionLink("See all restaurants", "Index", "Restaurants")</p>
  <p>@Html.ActionLink("create a new restaurant", "Create", "Restaurants")</p>
</div>

BestRestaurants/Views/Restaurants/AddType.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<h1>Adding a Type of food to Restaurant</h1>

<h4>Adding type to @Html.DisplayFor(model => model.Name)</h4>

@using (@Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)

  @Html.Label("Select the Type of food")
  @Html.DropDownList("TypeId")

  <input type="submit" value="Save"/>
}

@Html.ActionLink("Show all restaurants", "Index")

BestRestaurants/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant
<h4>Add a new restaurant</h4>

@using (Html.BeginForm())
{
  @Html.Label("Type")
  @Html.DropDownList("TypeId")
  <br>
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Rating)
  @Html.TextBoxFor(model => model.Rating, new { type = "number", min = "0", max = "5" })
  <br> 
  @Html.LabelFor(model => model.Cost)
  @Html.TextBoxFor(model => model.Cost, new { type = "number", min = "0", max = "3" })
  <br><br>
  <!--Review-->
  @Html.LabelFor(model => model.Review) <span>(max 255 characters):</span><br>
  @Html.TextAreaFor(model => model.Review, new { cols = "60", rows = "5", maxlength = "255"})
  <br>
  <input type="submit" value="Add New Restaurant" class="btn btn-default" />
}
<p>
  @Html.ActionLink("Show all restaurants", "Index")
</p> 

BestRestaurants/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="delete"/>
}

@Html.ActionLink("Back", "Index")

BestRestaurants/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant;

<h2>Restaurant Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This restaurant does not contain any types of food</p>
}
else
{
  <h4>Types of food served at the restaurant:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Type.TypeName</li>
  }
  </ul>
}

<p>@Html.ActionLink("Add a Type to this Restaurant", "AddType", new {id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Back", "Index")</p>
<p>@Html.ActionLink("Edit Restaurant", "Edit", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Delete Restaurant", "Delete", new { id = Model.RestaurantId })</p>

BestRestaurants/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<h2>Edit</h2>

<h4>Edit this restaurant: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="save"/>
}

<p>@Html.ActionLink("Back", "Index")</p>

BestRestaurants/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Restaurant>;

<h1>Your Reviewed Restaurants</h1>

@if (@Model.Count == 0)
{
  <h3>
    You haven't reviewed any restaurants yet!
  </h3>
}

<ul>
  @foreach(Restaurant restaurant in Model)
  {
    <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId })</li>
  }
</ul>

<p>
  @Html.ActionLink("Review a Restaurant", "Create")
</p>
<p>
  @Html.ActionLink("See all food types", "Index", "Types")
</p>

<p>@Html.ActionLink("Return Home", "Index", "Home")</p>

BestRestaurants/Views/Shared/Footer.cshtml
<div id="footer">
  FOOTER
</div>

BestRestaurants/Views/Shared/Header.cshtml
<div id="header">
  HEADER 
</div>

BestRestaurants/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My To-Do List!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
    @await Html.PartialAsync("Footer")
  </body>
</html>

BestRestaurants/Views/Types/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Type;

<h2>Add a Restaurant Type!</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.TypeName)
  @Html.TextBoxFor(model => model.TypeName)

  <input type="submit" value="Add Type">
}

<p>@Html.ActionLink("Return Home", "Index", "Home")</p>

BestRestaurants/Views/Types/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Type;

<h2>Removing a Restaurant type:</h2>

@using (Html.BeginForm())
{
  <p>Delete the Restaurant type @Model.TypeName</p>
  <input type="submit" label="Confirm">
}

<p>@Html.ActionLink("See all food types", "Index", "Types")</p>
<p>@Html.ActionLink("See All Restaurants", "Index", "Restaurants")</p>
<p>@Html.ActionLink("Return Home", "Index", "Home")</p>

BestRestaurants/Views/Types/Details.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;

<h2>Details For @Model.TypeName</h2>

@if (Model.JoinEntities.Count == 0)
{
  <p>This cuisint type has no Restaurants bound to it!!!</p>
}

<ul>
  @foreach (var join in Model.JoinEntities)
  {
    <li>@Html.ActionLink($"{join.Restaurant.Name}", "Details" ,"Restaurants", new { id = join.Restaurant.RestaurantId})</li>
  }
</ul>

<p>@Html.ActionLink("See all food types", "Index", "Types")</p>
<p>@Html.ActionLink("See All Restaurants", "Index", "Restaurants")</p>
<p>@Html.ActionLink("Return Home", "Index", "Home")</p>

BestRestaurants/Views/Types/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Type

<h1>EDIT</h1>

<h3>You are editing the information for the Type: @Html.DisplayFor(model => model.TypeName)</h3>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TypeId)

  @Html.LabelFor(model => model.TypeName)
  @Html.EditorFor(model => model.TypeName)

  <input type="submit" value="Save"/>
}

<p>@Html.ActionLink("See all food types", "Index", "Types")</p>
<p>@Html.ActionLink("See All Restaurants", "Index", "Restaurants")</p>
<p>@Html.ActionLink("Return Home", "Index", "Home")</p>

BestRestaurants/Views/Types/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;

<h1>All Restaurant Types:</h1>

@if (Model.Count == 0)
{
  <p>There are no restaurant types?</p>
}

<ul>
  @foreach (BestRestaurants.Models.Type type in Model)
  {
    <li>@Html.ActionLink($"{type.TypeName}", "Details", new {id = type.TypeId})</li>
  }
</ul>

<p>@Html.ActionLink("Create a restaurant type", "Create")</p>
<p>@Html.ActionLink("See All Restaurants", "Index", "Restaurants")</p>
<p>@Html.ActionLink("Return Home", "Index", "Home")</p>